Rama1
infabeti/R3-Alberto-Aida-Inaki-Ander pull request #1
Opened 2021-01-21 18:58 UTC by InakiSagrario

La carpeta RETO3 es sin el node y la carpeta Reto3Des es con el node. El comando para activar el server es ( npm run dev ).

2021-01-26 09:51 UTC, infabeti commented on RETO3/script/GeoFunciones.js
> +});
Estás repitiendo lo mismo un montón de veces. Porque, no creas una función generica a la que le pasas unas configuraciones que estén en un archivo estático?

2021-01-26 09:53 UTC, infabeti commented on Reto3Des/app.js
> +const app = express();
Sería interesante que añadierais un control de errores

2021-01-26 09:54 UTC, infabeti commented on Reto3Des/public/script/GeoFunciones.js
> +var latitud = 43.28526202942883;
Lo mismo que antes cread una generica y pasarle unas configuraciones dependiendo de las necesidades

2021-01-26 09:55 UTC, infabeti commented on Reto3Des/public/script/formuario.js
> +if (document.formulario.nombre.value.length==0)
Teneis otro igual, está repetido

2021-01-26 09:56 UTC, infabeti requested changes
Teneis código repetido, cread un único método genérico. Y, también faltan los tests.

2021-01-27 14:32 UTC, alberto-garcia-lo commented on Reto3Des/public/script/formuario.js
> +if (document.formulario.nombre.value.length==0)
no esta repetido

2021-01-27 15:49 UTC, alberto-garcia-lo commented on Reto3Des/app.js
> +const app = express();
realizado

2021-01-27 15:51 UTC, InakiSagrario commented on RETO3/script/GeoFunciones.js
> +});
ya esta corregido

2021-02-01 17:51 UTC, merged